sudo: false
language: python
branches:
  except: [cookiecutter]
cache: pip
jobs:
  include:
  - {stage: check, python: '3.5', env: TOX_ENV=setup}
  - {stage: check, python: '3.5', env: TOX_ENV=safety}
  - {stage: check, python: '3.5', env: TOX_ENV=style}
  - {stage: check, python: '3.5', env: TOX_ENV=docs}
  - {stage: check, python: '3.5', env: TOX_ENV=spell}
  - {stage: check, python: '3.5', env: TOX_ENV=link}
  - {stage: test, after_success: 'tox -e codacy', python: '3.5', env: TOX_ENV=py35-django111}
  - {stage: test, after_success: 'tox -e codacy', python: '3.5', env: TOX_ENV=py35-django21}
  - {stage: test, after_success: 'tox -e codacy', python: '3.5', env: TOX_ENV=py35-django22}
  - {stage: test, after_success: 'tox -e codacy', python: '3.6', env: TOX_ENV=py36-django111}
  - {stage: test, after_success: 'tox -e codacy', python: '3.6', env: TOX_ENV=py36-django21}
  - {stage: test, after_success: 'tox -e codacy', python: '3.6', env: TOX_ENV=py36-django22}
  - {stage: test, after_success: 'tox -e codacy', python: 3.7-dev, env: TOX_ENV=py37-django111}
  - {stage: test, after_success: 'tox -e codacy', python: 3.7-dev, env: TOX_ENV=py37-django21}
  - {stage: test, after_success: 'tox -e codacy', python: 3.7-dev, env: TOX_ENV=py37-django22}
  - {stage: test, after_success: 'tox -e codacy', python: pypy, env: TOX_ENV=pypy-django111}
  - {stage: test, after_success: 'tox -e codacy', python: pypy, env: TOX_ENV=pypy-django21}
  - {stage: test, after_success: 'tox -e codacy', python: pypy, env: TOX_ENV=pypy-django22}
  fast_finish: true
  allow_failures:
  - {stage: check, env: TOX_ENV=style}
  - {stage: check, env: TOX_ENV=spell}
  - {stage: check, env: TOX_ENV=link}
  - {stage: test, python: pypy}
addons:
  apt:
    packages: [libenchant-dev]
install: [pip install -r requirements/ci.txt]
script: ['tox -e ${TOX_ENV}']
